CREATE TABLE IF NOT EXISTS "scm_vender" (
                                            "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                            "vender_var" int NOT NULL,
                                            "code" varchar NOT NULL,
                                            "name" varchar NOT NULL,
                                            "name_eng" varchar NOT NULL,
                                            "name_short" varchar NOT NULL,
                                            "country_id" int NOT NULL,
                                            "province_id" int NOT NULL,
                                            "city_id" int NOT NULL,
                                            "address" varchar NOT NULL,
                                            "phone" varchar NOT NULL,
                                            "abroad_flag" bit NOT NULL,
                                            "license_no" varchar NOT NULL,
                                            "currency_type" varchar NOT NULL,
                                            "tax_rate" int NOT NULL,
                                            "status_type" varchar NOT NULL,
                                            "creator" varchar DEFAULT '',
                                            "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                            "updater" varchar DEFAULT '',
                                            "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                            "deleted" bit NOT NULL DEFAULT FALSE,
                                            PRIMARY KEY ("id")
    ) COMMENT '供应商信息表';
----------------------------
-- Table structure for scm_purchase_plan
-- ----------------------------
DROP TABLE IF EXISTS `scm_purchase_plan`;
CREATE TABLE `scm_purchase_plan_test` (
                                     `id` bigint NOT NULL COMMENT '主键',
                                     `code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '采购计划单号',
                                     `plan_date` datetime DEFAULT NULL COMMENT '计划日期',
                                     `plan_type` tinyint NOT NULL COMMENT '计划类型',
                                     `audit_status` tinyint DEFAULT NULL COMMENT '单据状态',
                                     `applyer_id` bigint NOT NULL COMMENT '申请人',
                                     `apply_dept_id` bigint DEFAULT NULL COMMENT '申请人部门',
                                     `source_id` bigint DEFAULT NULL COMMENT '来源单主键',
                                     `source_type` tinyint DEFAULT NULL COMMENT '来源类型',
                                     `source_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '来源单号',
                                     `convert_flag` tinyint DEFAULT NULL COMMENT '转合同状态  0-否 1-是',
                                     `print_flag` tinyint DEFAULT NULL COMMENT '打印状态  0-否 1-是',
                                     `print_times` int DEFAULT 0 COMMENT '打印次数',
                                     `input_user_id` bigint DEFAULT NULL COMMENT '录入人',
                                     `input_date` datetime DEFAULT NULL COMMENT '录入日期',
                                     `audit_user_id` bigint DEFAULT NULL COMMENT '审核人',
                                     `audit_date` datetime DEFAULT NULL COMMENT '审核日期',
                                     `comments` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
                                     `close_reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '结案原因',
                                     `cust_contract` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '客户合同号',
                                     `dest_port` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '目的口岸',
                                     `business_id` bigint DEFAULT NULL COMMENT '业务员',
                                     `deliver_date` datetime DEFAULT NULL COMMENT '交货日期',
                                     `jbpm_instanse_id` varchar(32) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '流程实例主键',
                                     `creator` int unsigned DEFAULT NULL COMMENT '创建人',
                                     `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                     `updater` int unsigned DEFAULT NULL COMMENT '修改人',
                                     `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
                                     `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '删除  0：有效 1：删除',
                                     PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='采购计划';

-- ----------------------------
-- Table structure for scm_purchase_plan_product
-- ----------------------------
DROP TABLE IF EXISTS `scm_purchase_plan_product`;
CREATE TABLE `scm_purchase_plan_product_test` (
                                             `id` bigint NOT NULL COMMENT '主键',
                                             `plan_id` bigint NOT NULL COMMENT '采购计划主键',
                                             `product_id` bigint NOT NULL COMMENT '产品主键',
                                             `product_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '产品编号',
                                             `product_name` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '产品名称',
                                             `unit` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '单位',
                                             `cust_goods_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '客户货号',
                                             `quantity` int DEFAULT NULL COMMENT '计划数量',
                                             `amount` decimal(19,6) DEFAULT NULL COMMENT '金额',
                                             `expect_deliver_date` datetime DEFAULT NULL COMMENT '预计交期',
                                             `out_contract_no` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '外销合同',
                                             `serial_no` int DEFAULT NULL COMMENT '订单序号',
                                             `pur_order_id` bigint DEFAULT NULL COMMENT '采购单主键',
                                             `pur_order_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '采购单号',
                                             `pur_order_serial_no` int DEFAULT NULL COMMENT '采购单序号',
                                             `creator` int unsigned DEFAULT NULL COMMENT '创建人',
                                             `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                             `updater` int unsigned DEFAULT NULL COMMENT '修改人',
                                             `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
                                             `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '删除  0：有效 1：删除',
                                             PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='采购计划-商品表';
